### ISSUE TITLE
Be able to summon/looping through previous prompts by using the arrow keys

### ISSUE THREAD

**Issue by Swop** [ekkinox/yo#1]
Since some tasks would be a bit repetitive (ex: `"try to do this"`, `"oh, I'm missing dependencies"`, `"try to install them, then"`, `"try to do the first thing again"`), or simply because sometimes you want to do something multiple times (like checking the status of something etc.), it could be convenient to be able to use the arrow keys to loop through prompt history, just like we can do with a classic shell.

Since `hey` is running the expected commands under the hood, the executed commands are not inserted in the shell history, so having such a feature in the `hey` prompt/REPL could be a good alternative.

**Comment by ekkinox** [comment]
The TUI has been completely refactored.

You can now use `up` or `down` arrows when the prompt is focused to navigate in your history.
