### ISSUE TITLE
Doesn't ask for OpenAI API key

### ISSUE THREAD

**Issue by supagroova** [ekkinox/yo#7]
When running for the first time it doesn't ask for OpenAI credentials as expected (from the README).

It appears that perhaps the placeholder 'xxx' is being used.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/36730/229998337-ea2825f8-0304-47c2-8616-7f94aa8ee0f2.png">

**Comment by supagroova** [comment]
[UPDATE] Even with the API key correctly set as per the example in the `~/.config/yo.json` I still get this error.

**Comment by ekkinox** [comment]
did you pull the repo ?

**Comment by supagroova** [comment]
That must have been it. 👍
